<?php
/** @var string $CLOUDY_CORE_DIR */
/** @var string $CLOUDY_CACHE_DIR */
/** @var string $CLOUDY_PACKAGE_CONTROLLER */
/** @var string $CLOUDY_PACKAGE_CONFIG */
/** @var string $CLOUDY_BASEPATH */
/** @var string $CLOUDY_RUNTIME_UUID */

$data = [
  'CLOUDY_CORE_DIR' => $CLOUDY_CORE_DIR,
  'CLOUDY_CACHE_DIR' => $CLOUDY_CACHE_DIR,
  'CLOUDY_PACKAGE_CONTROLLER' => $CLOUDY_PACKAGE_CONTROLLER,
  'CLOUDY_PACKAGE_CONFIG' => $CLOUDY_PACKAGE_CONFIG,
  'CLOUDY_BASEPATH' => $CLOUDY_BASEPATH,
  'CLOUDY_RUNTIME_UUID' => $CLOUDY_RUNTIME_UUID,
];
echo json_encode($data);
